service: sns-udemy-api
plugins:
  - serverless-plugin-tracing
  - serverless-apigw-binary
  - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: ap-northeast-1
  apiGateway:
    binaryMediaTypes:
      - "*/*"
  environment:
    DATABASE_URL: "postgresql://postgres:shincode0712@db.deerbjwxumptocxcgflb.supabase.co:5432/postgres"
    JWT_SECRET: "your_jwt_secret_key"
    NODE_ENV: "production"

functions:
  app:
    handler: server.handler
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: "{proxy+}"
          method: ANY
          cors: true

custom:
  apigwBinary:
    types:
      - "*/*"
  serverless-offline:
    httpPort: 3000

package:
  excludeDevDependencies: true
  exclude:
    - ./**
    - "!server.js"
    - "!node_modules/**"
    - node_modules/**/*.test.js
    - node_modules/**/*{test,spec}.js
    - node_modules/**/*test*/
    - node_modules/**/__test__*
    - node_modules/graphlib/** # この行を追加
